# Generated by Django 2.1.4 on 2019-02-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0004_state_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='state',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
